Repository Team-E2I4/Team-E2I4-TikiTaza-BE, pull requests merged in 2024-03, with the labels that each got.

#57 refactor: 1차 리팩토링 진행
  api/src/main/java/com/pgms/api/domain/game/service/GameRoomService.java
  api/src/main/java/com/pgms/api/domain/game/service/GameService.java
  api/src/main/java/com/pgms/api/socket/service/GameMessageService.java
  api/src/main/java/com/pgms/api/socket/service/GameRoomMessageService.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisRepository.java
  http/test.http
Labels: refactor

#60 feat: 인게임 메세지 allMembers와 score 통합
  api/src/main/java/com/pgms/api/domain/game/dto/response/InGameMemberGetResponse.java
  api/src/main/java/com/pgms/api/domain/game/service/GameService.java
  api/src/main/java/com/pgms/api/socket/dto/response/GameMessage.java
  api/src/main/java/com/pgms/api/socket/service/GameMessageService.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisRepository.java
Labels: feat, game

#61 refactor: RedisRepository 분리
  api/src/main/java/com/pgms/api/domain/game/service/GameRoomService.java
  api/src/main/java/com/pgms/api/domain/game/service/GameService.java
  api/src/main/java/com/pgms/api/domain/member/service/AuthService.java
  api/src/main/java/com/pgms/api/domain/member/service/MemberService.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameHistory.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameQuestion.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisInGameRepository.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisKeyRepository.java
  core/core-security/src/main/java/com/pgms/coresecurity/jwt/JwtTokenProvider.java
Labels: refactor

#63 feat: 랭킹 기능 레디스로 이전
  api/src/main/java/com/pgms/api/domain/game/dto/response/GameRoomMemberGetResponse.java
  api/src/main/java/com/pgms/api/domain/game/service/GameRoomService.java
  api/src/main/java/com/pgms/api/domain/game/service/GameService.java
  api/src/main/java/com/pgms/api/domain/member/dto/response/AccountGetResponse.java
  api/src/main/java/com/pgms/api/domain/member/service/MemberService.java
  api/src/main/java/com/pgms/api/domain/rank/controller/RankController.java
  api/src/main/java/com/pgms/api/domain/rank/dto/MemberRankResponse.java
  api/src/main/java/com/pgms/api/domain/rank/service/RankService.java
  api/src/main/java/com/pgms/api/domain/rank/service/RankingService.java
  api/src/main/java/com/pgms/api/scheduler/RankingScheduler.java
  api/src/main/java/com/pgms/api/socket/dto/request/GameFinishRequest.java
  api/src/main/resources/db/data.sql
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameHistory.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameRank.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/member/Member.java
  core/core-domain/src/main/java/com/pgms/coredomain/repository/GameRankRepository.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/dto/RankingRequest.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/dto/RankingResponse.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisRankingRepository.java
Labels: refactor, rank

#67 feat: Redis 랭킹 산정 가중치 로직 추가
  api/src/main/java/com/pgms/api/domain/game/service/GameService.java
  api/src/main/java/com/pgms/api/socket/controller/GameSocketController.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisInGameRepository.java
Labels: feat

#69 feat: 게스트 로그인 시 리프레시 토큰 발급 로직 삭제 처리 및 로그아웃 처리 수정
  api/src/main/java/com/pgms/api/domain/game/service/GameService.java
  api/src/main/java/com/pgms/api/domain/member/controller/AuthController.java
  api/src/main/java/com/pgms/api/domain/member/dto/response/GuestResponse.java
  api/src/main/java/com/pgms/api/domain/member/service/AuthService.java
  api/src/main/java/com/pgms/api/socket/controller/GameSocketController.java
Labels: feat, member

#70 refactor: 전반적인 리팩토링 진행 및 DB index & 제약조건 추가
  .github/workflows/ci.yml
  api/src/main/java/com/pgms/api/domain/member/service/AuthService.java
  api/src/main/java/com/pgms/api/domain/member/service/KakaoOauthService.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameHistory.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameInfo.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameQuestion.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameRoom.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameRoomMember.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/member/Member.java
  core/core-domain/src/main/java/com/pgms/coredomain/repository/GameRoomMemberRepository.java
  core/core-infra-db/src/main/java/com/pgms/coreinfradb/config/QueryDslConfig.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisInGameRepository.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisKeyRepository.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisRankingRepository.java
Labels: refactor

#71 refactor: 전반적인 코드 리팩토링 및 DB 인덱스 & 제약조건 추가
  .aws/task-definition-dev.json
  .github/workflows/cd-dev.yml
  .github/workflows/ci.yml
  api/src/main/java/com/pgms/api/domain/member/service/AuthService.java
  api/src/main/java/com/pgms/api/domain/member/service/KakaoOauthService.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameHistory.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameInfo.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameQuestion.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameRoom.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/game/GameRoomMember.java
  core/core-domain/src/main/java/com/pgms/coredomain/domain/member/Member.java
  core/core-domain/src/main/java/com/pgms/coredomain/repository/GameRoomMemberRepository.java
  core/core-infra-db/src/main/java/com/pgms/coreinfradb/config/QueryDslConfig.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisInGameRepository.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisKeyRepository.java
  core/core-infra-redis/src/main/java/com/pgms/coreinfraredis/repository/RedisRankingRepository.java
Labels: refactor

#72 cd: prod cd 환경이름 변경 & data.sql 수정
  .github/workflows/cd-prod.yml
  api/src/main/resources/db/data.sql
Labels: cd
